services:
  # 1. Backend: Nexus Sentinel API
  - type: web
    name: nexus-sentinel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATAHUB_GMS_URL
        sync: false # This tells Render to ask you for the value privately

  # 2. Frontend: Nexus Sentinel Dashboard
  - type: web
    name: nexus-sentinel-ui
    env: static
    buildCommand: cd nexus-frontend && npm install && npm run build
    publishPath: ./nexus-frontend/dist